import Link from "next/link";
import { ArrowUpRight, BookOpen } from "lucide-react";
import { getLang } from "@/lib/i18n";

export const metadata = { title: "Admissions guide" };
export default async function AdmissionsGuide() {
  const uz = await getLang() === "uz";
  // Original Sirius reading material. No competitor course videos or transcripts.
  const lessons = [
    { title: uz ? "Universitetlarni o‘rganish" : "Researching colleges", body: uz ? "Har bir universitet uchun yo‘nalish, o‘qish xarajati, joylashuv va ariza talablarini alohida yozing. Sirius’dagi ma’lumotni boshlang‘ich nuqta sifatida ishlating; joriy muddat va talabni universitetning rasmiy sahifasidan tekshiring. Saqlangan ro‘yxatingizda nima sababdan aynan shu universitetni tanlaganingizni yozib boring." : "Record the program, cost, location and application requirements for each college. Use Sirius as a research starting point and confirm current dates and requirements on the college's official website. Keep a reason for each college on your shortlist.", href: "/universities" },
    { title: uz ? "Faoliyatlarni tavsiflash" : "Describing activities", body: uz ? "Faoliyat nomidan keyin siz bajargan ish, ajratgan vaqt va aniq natijani yozing. Jamoa qilgan ishni shaxsiy yutuq sifatida ko‘rsatmang. O‘lchov bo‘lsa, uning manbasini saqlang. Tajribani qisqa va tekshiriladigan jumlalarga aylantiring." : "Record your role, the work you did, the time involved and the outcome. Distinguish your contribution from the team's work. Keep evidence for measurable results, then write concise descriptions.", href: "/activities" },
    { title: uz ? "Insho qoralamasini tayyorlash" : "Preparing an essay draft", body: uz ? "Savolni avval o‘qing va javob bermoqchi bo‘lgan bitta asosiy fikrni belgilang. Uni ko‘rsatadigan haqiqiy voqeani tanlang. Birinchi versiyada fikrlar tartibiga e’tibor bering, keyin takrorlar va ortiqcha jumlalarni qisqartiring. Editor versiyalar tarixini saqlaydi; o‘zgartirishdan oldin eski versiyani solishtiring." : "Read the prompt and identify the main point you want to communicate. Choose a real experience that supports it. Organize ideas in the first draft, then remove repetition. Use version history to compare revisions before making further changes.", href: "/essay-editor" },
    { title: uz ? "Ariza checklisti" : "Application checklists", body: uz ? "Har bir universitet uchun alohida ariza oching. Deadline, insho, tavsiyanoma va boshqa kerakli vazifalarni checklistga yozing. Vazifani faqat bajarilganda belgilang. Checklistni universitet talablari o‘zgarganda yangilang va shaxsiy hujjatlaringizni ehtiyotkorlik bilan saqlang." : "Create an application for each college. Add its deadline and the essay, recommendation and other tasks it requires. Mark a task complete only when it is done. Update your checklist when requirements change and store personal documents carefully.", href: "/applications/tracker" },
    { title: uz ? "Tayyorgarlikni rejalash" : "Planning preparation", body: uz ? "Haftada ajrata oladigan vaqtingizni profilga kiriting. Rejadagi vazifani kichik sessiyalarga bo‘ling. Mashqdan so‘ng faqat ballni emas, xato javob va izohni ham ko‘ring. Tugagan sessiyalar Insights bo‘limida saqlanadi." : "Set realistic weekly study time in your profile. Split study tasks into smaller sessions. After practice, review errors and explanations as well as the score. Completed sessions appear in Insights.", href: "/plan" },
    { title: uz ? "Yakuniy tekshiruv" : "Final review", body: uz ? "Arizani topshirishdan oldin ism, sana, universitet nomi, savolga mos javob va so‘z limitini tekshiring. Boshqa universitet uchun yozilgan jumlalarni tasodifan qoldirmang. Ariza topshirilgach, holatini yangilang va tasdiqni o‘zingizning ishonchli saqlash joyingizda saqlang." : "Before submitting, review names, dates, college references, prompt relevance and word limits. Remove accidental references to another college. After submission, update the application status and keep the confirmation in your own secure storage.", href: "/admissions-analysis" },
  ];
  return <div className="mx-auto max-w-5xl space-y-7"><header><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Prepare · Admissions</p><h1 className="mt-3 font-extrabold">{uz ? "Admissions qo‘llanma" : "Admissions guide"}</h1><p className="mt-3 text-muted-foreground">{uz ? "Universitetga ariza tayyorlash bo‘yicha qisqa amaliy bo‘limlar." : "Short practical reading sections for preparing college applications."}</p></header><div className="space-y-4">{lessons.map((lesson, index) => <details key={lesson.href} className="group rounded-2xl border border-border/60 bg-card p-6"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-4"><span className="text-xs font-bold text-muted-foreground">{String(index+1).padStart(2,"0")}</span><h2 className="flex-1 text-base font-semibold">{lesson.title}</h2><BookOpen className="size-5 text-primary" /></summary><div className="mt-4 border-t border-border pt-4"><p className="text-sm leading-7 text-muted-foreground">{lesson.body}</p><Link href={lesson.href} className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-primary">{uz ? "Tegishli vositani ochish" : "Open the relevant tool"}<ArrowUpRight className="size-4" /></Link></div></details>)}</div></div>;
}
